name: "Bug"
on: 
  push:

jobs:
  bug:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3    
    - shell: bash -l {0}
      run: |
        wget "https://github.com/mamba-org/micromamba-releases/releases/download/1.5.6-0/micromamba-osx-64" -O /usr/local/bin/micromamba
        chmod +x /usr/local/bin/micromamba

        # Start reproducer
        ./test.sh
